name: 'Publish Conda package to Anaconda.org'
description: 'Build and Publish conda package to Anaconda'
author: 'Andrew Prokhorenkov, modified by Maxime Borry, modified by Luis Fabregas'
branding:
  icon: 'package'  
  color: 'purple'
inputs: 
  subDir:
    description: 'Sub-directory with conda recipe'
    default: '.'
  AnacondaToken:
    description: 'Anaconda access Token'
  platforms:
    description: 'Platforms to build and publish [osx linux win]'
    default: 'win osx linux'
  arch:
    description: 'Architecture to build and publish [32 64]'
    default: '64'    
runs:
  using: 'docker'
  image: 'Dockerfile'
